# String Assignment (20 Drills)

name = "Jason"
greeting = "Hello"
status = "Active"
city = "Tokyo"
language = "Python"
role = "Admin"
food = "Pizza"
color = "Blue"
emotion = "Happy"
device = "Laptop"
weather = "Cloudy"
title = "Mr."
category = "Tech"
filename = "report.pdf"
animal = "Dog"
genre = "Horror"
brand = "Nike"
country = "Canada"
message = "Welcome back!"
day = "Monday"